// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpartanRoomsData;

namespace SpartanRoomsData.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191101115353_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpartanRoomsData.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("SpartanRoomsData.Models.Reservation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservationString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomID")
                        .HasColumnType("int");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RoomID");

                    b.HasIndex("StudentID");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("SpartanRoomsData.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("departmentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("departmentID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SpartanRoomsData.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RoomID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("SpartanRoomsData.Models.UnlockInstruction", b =>
                {
                    b.Property<int>("UnlockInstructionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Instruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomID")
                        .HasColumnType("int");

                    b.Property<int>("UnlockType")
                        .HasColumnType("int");

                    b.HasKey("UnlockInstructionID");

                    b.HasIndex("RoomID");

                    b.ToTable("UnlockInstruction");
                });

            modelBuilder.Entity("SpartanRoomsData.Models.Reservation", b =>
                {
                    b.HasOne("SpartanRoomsData.Models.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomID");

                    b.HasOne("SpartanRoomsData.Models.Student", "Student")
                        .WithMany("Reservations")
                        .HasForeignKey("StudentID");
                });

            modelBuilder.Entity("SpartanRoomsData.Models.Room", b =>
                {
                    b.HasOne("SpartanRoomsData.Models.Department", "department")
                        .WithMany("Rooms")
                        .HasForeignKey("departmentID");
                });

            modelBuilder.Entity("SpartanRoomsData.Models.Student", b =>
                {
                    b.HasOne("SpartanRoomsData.Models.Room", null)
                        .WithMany("Students")
                        .HasForeignKey("RoomID");
                });

            modelBuilder.Entity("SpartanRoomsData.Models.UnlockInstruction", b =>
                {
                    b.HasOne("SpartanRoomsData.Models.Room", null)
                        .WithMany("UnlockInstructions")
                        .HasForeignKey("RoomID");
                });
#pragma warning restore 612, 618
        }
    }
}
